### ISSUE TITLE
Refactor the Logic for Previous/Next

### ISSUE THREAD

**Issue by nishantbalaji** [UCSD-E4E/Pyrenote#135]
The current logic for Previous/Next files are very state dependent and should be cleaned up and refactored so it calls the backend and properly counts each file. This may involve refactoring how we store audio clips in each project to be more numerical as the "All" tab is out of order. In this particular example, the pages go from 13 -> 2 -> 5 (and vice versa when clicked previous) so we should instead just go in numerical order with the dataId's of each clip.  
![image](https://user-images.githubusercontent.com/44332326/126021069-ca4db8c1-bf32-4174-8b5c-4d9ccfb0be5c.png)

We need to also account for users annotating clips out of order and jumping to the proper clip in the "Yet to Annotate" tab, "Annotated" tab, and "Marked for Review" tab.

**Comment by Sean1572** [comment]
Alternatively, we can abstract away this section with a quick start button
Sort of just have a start annotating now on the project selection page so they don't have to access this page

I have a frist pass idea of this abstraction on the Next-Button_Rework branch

**Comment by Sean1572** [comment]
I've spent some time thinking about this
If the user annotates in a random order then the next buttons would break in this implementation. If we have 1 -> 2 -> 3, and the user annotates 2 goes back, the next buttons would need to handle the case where we must skip, some times serval data points in a row.

**Comment by Sean1572** [comment]
![image](https://user-images.githubusercontent.com/25123131/128784746-0d467df8-9065-4f10-8946-d147a5e20cc0.png)
My personal example

**Comment by Sean1572** [comment]
Numerical order but not linear progression. Lets keep our implementation where we pull from the same list of data for now and see if we can fix up the frontend code to be a bit clearer

**Comment by Sean1572** [comment]
I'm working on a new implementation of this system at `next-button-get-data`. This implementation changes how we obtain the next data point and removes some of the complexity of the frontend code. On this branch I also have a recommend data api call where the system randomly gives the user precompleted clips from other users to review as a start to a more robust dynamic recommendation system
